services:
  api-getawey:
    build: ./api-getawey
    container_name: api-getawey
    ports:
      - "3000:3000"
    depends_on:
      - auth
    volumes:
      - ./api-getawey:/app
      - '/app/node_modules'
    networks:
      - app-network
  
  auth:
    build: ./auth
    container_name: auth
    ports:
      - "3001:3001"
    volumes:
      - ./auth:/app
      - '/app/node_modules'
    networks:
      - app-network

  notifications:
    build: ./notifications
    container_name: notifications
    ports:
      - "3002:3002"
    depends_on:
      - auth
    volumes:
      - ./notifications:/app
      - '/app/node_modules'
    networks:
      - app-network

  logs:
    build: ./logs
    container_name: logs
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - tasks
    volumes:
      - ./logs:/app
      - '/app/node_modules'
    networks:
      - app-network

  tasks:
    build: ./tasks
    container_name: tasks
    ports:
      - "3004:3004"
    volumes:
      - ./tasks:/app
      - '/app/node_modules'
    depends_on:
      - tasks-db
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq-taskflow-express
    image: rabbitmq:3.12.4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network

  auth-db:
    image: mongo:latest
    container_name: auth-db
    restart: always
    ports:
      - "27018:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./auth-db:/data/db

  logs-db:
    image: mongo:latest
    container_name: logs-db
    restart: always
    ports:
      - "27019:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./logs-db:/data/db

  tasks-db:
    image: postgres:latest
    container_name: tasks-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tasks
    networks:
      - app-network
    volumes:
      - ./tasks-db:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge