# Usa una imagen de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm install

# Copia el código fuente restante
COPY . .

# Expone el puerto 3004
EXPOSE 3004

# Comando para ejecutar la aplicación
# CMD ["npm", "run", "dev"]
CMD ["sh", "-c", "npm uninstall --save-dev mysql2 && npm uninstall pg && npm install mysql2 pg && npm run dev"]
