# Usa una imagen de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm install

# Copia el código fuente restante
COPY . .

# Expone el puerto 3001
EXPOSE 3001

# Comando para ejecutar la aplicación
# CMD ["npm", "run", "dev"]
CMD ["sh", "-c", "npm uninstall --save-dev bcrypt && npm install bcrypt && npm run dev"]
